# config/config.py

IN_STEPS = 8
OUT_STEPS = 4

TIME_INTERVAL_HOURS = 6

INPUT_HOURS = IN_STEPS * TIME_INTERVAL_HOURS
OUTPUT_HOURS = OUT_STEPS * TIME_INTERVAL_HOURS

PATCH_SIZE = 4
EMBED_DIM = 128
NUM_BLOCKS = 6

BATCH_SIZE = 4
LEARNING_RATE = 1e-4
EPOCHS = 30